# version: '3.8'

# services:
#   db:
#     image: postgres
#     restart: always
#     container_name: postgres
#     environment:
#       POSTGRES_DB: hw11
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"

# version: '3.9'
# services:
#   redis:
#     image: redis:alpine
#     ports:
#       - "6379:6379"
#   postgres:
#     image: postgres
#     environment:
#       POSTGRES_DB: hw11
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data

version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data